STATUS_ACCEPTED = 'ACCEPT'
STATUS_PENDING = 'MANUAL_REVIEW'
STATUS_DECLINED = 'DENY'

KYC_STATE_ACCEPTED = 'A'
KYC_STATE_PENDING = 'R'
KYC_STATE_DECLINED = 'D'

STATUS_MAP = {
    KYC_STATE_ACCEPTED: STATUS_ACCEPTED,
    KYC_STATE_PENDING: STATUS_PENDING,
    KYC_STATE_DECLINED: STATUS_DECLINED,
}

USER_REPUTATION_TRUSTED = 'TRUSTED'
USER_REPUTATION_UNKNOWN = 'UNKNOWN'
USER_REPUTATION_SUSPICIOUS = 'SUSPICIOUS'
USER_REPUTATION_BAD = 'BAD'
